name: CI

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  # ----------------------- TESTING, LINTING, AND BUILDING -----------------------------
  test-lint-build:
    name: Test, Lint, and Build Apps
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-deps
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-deps

      # Testing and linting
      - name: Install npm dependencies, Test, and Lint
        run: |
          npm install
          npm test
          npx eslint

      # Build Android App
      - name: Build Android App
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk
          mkdir -p android/app/build/intermediates/assets/release/
          npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/build/intermediates/assets/release/index.android.bundle --assets-dest android/app/build/intermediates/res/merged/release
          cd android
          chmod +x gradlew
          ./gradlew clean
          ./gradlew bundleRelease -Pkeystore.password=${{ secrets.KEYSTORE_PASSWORD }}

      # Build iOS App
      - name: Build iOS App
        if: runner.os == 'macOS'
        run: |
          gem install cocoapods
          cd ios && pod install
          xcodebuild -workspace lumen_nextgen_mobile.xcworkspace -scheme lumen_nextgen_mobile -sdk iphonesimulator -configuration Debug build
