name: CI

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  # ----------------------- COMMON -----------------------------
  common:
    name: Common Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install npm dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Lint
        run: npx eslint

  # ----------------------- ANDROID -----------------------------
  build-android:
    name: Build Android App & Release APK
    runs-on: ubuntu-latest
    needs: common
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Install Android SDK
        uses: android-actions/setup-android@v2

      - name: Prepare Android App Bundle
        run: |
          mkdir -p android/app/build/intermediates/assets/release/
          npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/build/intermediates/assets/release/index.android.bundle --assets-dest android/app/build/intermediates/res/merged/release

  # ----------------------- IOS -----------------------------
  build-ios:
    name: Build iOS App
    runs-on: macos-latest
    needs: common
    steps:
      - name: Install CocoaPods
        run: gem install cocoapods

      - name: Cache Pods
        uses: actions/cache@v4
        id: pods-cache
        with:
          path: ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install iOS dependencies
        run: cd ios && pod install

      - name: Build iOS
        run: cd ios && xcodebuild -workspace lumen_nextgen_mobile.xcworkspace -scheme lumen_nextgen_mobile -sdk iphonesimulator -configuration Debug build
