name: CI

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  ci:
    runs-on: macos-latest
    strategy:
      matrix:
        target: [test-and-lint, build-android, build-ios]
        node-version: [22]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-deps
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-deps

      - name: Install npm dependencies
        run: npm install

      # ----------------------- TESTING AND LINTING -----------------------------
      - name: Run tests
        if: matrix.target == 'test-and-lint'
        run: npm test

      - name: Lint
        if: matrix.target == 'test-and-lint'
        run: npx eslint .

      # ----------------------- ANDROID -----------------------------
      - name: Set up JDK 17
        if: matrix.target == 'build-android'
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

      - name: Validate Gradle wrapper
        if: matrix.target == 'build-android'
        uses: gradle/wrapper-validation-action@v1

      - name: Install Android SDK
        if: matrix.target == 'build-android'
        uses: android-actions/setup-android@v2

      - name: Prepare Android App Bundle
        if: matrix.target == 'build-android'
        run: |
          mkdir -p android/app/build/intermediates/assets/release/
          npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/build/intermediates/assets/release/index.android.bundle --assets-dest android/app/build/intermediates/res/merged/release

      - name: Build Android
        if: matrix.target == 'build-android'
        run: |
          cd android
          chmod +x gradlew
          ./gradlew clean
          ./gradlew bundleRelease -Pkeystore.password=${{ secrets.KEYSTORE_PASSWORD }}

      # ----------------------- IOS -----------------------------
      - name: Install CocoaPods
        if: matrix.target == 'build-ios'
        run: gem install cocoapods

      - name: Cache CocoaPods
        if: matrix.target == 'build-ios'
        uses: actions/cache@v3
        with:
          path: ios/Pods
          key: ${{ runner.os }}-pods
          restore-keys: |
            ${{ runner.os }}-pods

      - name: Install iOS dependencies
        if: matrix.target == 'build-ios'
        run: cd ios && pod install

      - name: Build iOS
        if: matrix.target == 'build-ios'
        run: cd ios && xcodebuild -workspace lumen_nextgen_mobile.xcworkspace -scheme lumen_nextgen_mobile -sdk iphonesimulator -configuration Debug build
