name: CI

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  # # ----------------------- ANDROID -----------------------------
  # build-android:
  #   name: Build android app & release apk
  #   runs-on: ubuntu-latest
  #   steps:
  #     # Step 1: Checkout the repository
  #     - name: Checkout repository
  #       uses: actions/checkout@v2

  #     # Step 2: Set up Node.js environment
  #     - name: Set up Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '22'

  #     # Step 3: Install npm dependencies
  #     - name: Install dependencies
  #       run: npm install

  #     # Step 4: Run tests
  #     - name: Run tests
  #       run: npm test

  #     # Step 5: Run linter
  #     - name: Lint
  #       run: npx eslint

  #     # Step 6: Set up JDK 17
  #     - name: Set up JDK 17
  #       uses: actions/setup-java@v3
  #       with:
  #         java-version: '17'
  #         distribution: 'adopt'
  #         cache: "gradle"

  #     # Step 7: Validate Gradle wrapper
  #     - name: Validate Gradle wrapper
  #       uses: gradle/wrapper-validation-action@v1

  #     # Step 8: Install Android SDK
  #     - name: Install Android SDK
  #       uses: android-actions/setup-android@v2

  #     # Step 9: Prepare Android App Bundle
  #     - name: Prepare Android App Bundle
  #       run: |
  #         mkdir -p android/app/build/intermediates/assets/release/
  #         npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/build/intermediates/assets/release/index.android.bundle --assets-dest android/app/build/intermediates/res/merged/release

  #     # Step 10: Build Android Release
  #     - name: Build Android Release
  #       run: |
  #         cd android
  #         chmod +x gradlew 
  #         ./gradlew clean
  #         ./gradlew bundleRelease -Pkeystore.password=${{ secrets.KEYSTORE_PASSWORD }}

  #     # Step 11: Upload APK
  #     - name: Upload APK
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: release-apk
  #         path: android/app/build/outputs/apk/release/app-release.apk

      
      

  # ----------------------- IOS -----------------------------
  build-ios:
    runs-on: macos-latest
    steps:
      - name: check Xcode version
        run: /usr/bin/xcodebuild -version
        
      - name: checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Clean workspace
        run: |
          git clean -ffdx
          npm cache clean --force

      - name: Clean Xcode Build
        run: |
          cd ios
          xcodebuild clean -workspace your_app.xcworkspace -scheme your_app

      - name: install yarn dependencies
        run: |
          cd ios
          yarn install    

      - name: install Cocoapod dependencies
        run: |
          cd ios
          pod repo update
          pod install  

      - name: build archive
        run: |
          cd ios
          xcodebuild -workspace your_app.xcworkspace \
          -scheme "your_app" \
          -sdk iphoneos \
          -configuration Release \
          -destination generic/platform=iOS \
          -archivePath $RUNNER_TEMP/your_app.xcarchive \
          archive

      # - name: Build and Test
      #   env:
      #     XCODE_WORKSPACE: ios/lumen_nextgen_mobile.xcworkspace
      #     XCODE_SCHEME: lumen_nextgen_mobile
      #     XCODE_DESTINATION: 'platform=iOS Simulator,OS=14.5,name=iPhone 15'
      #   run: |
      #     set -o pipefail && xcodebuild clean -workspace $XCODE_WORKSPACE -scheme $XCODE_SCHEME -configuration Debug -sdk iphonesimulator | xcpretty
      #     set -o pipefail && xcodebuild build -workspace $XCODE_WORKSPACE -scheme $XCODE_SCHEME -destination "$XCODE_DESTINATION" | xcpretty
      #     set -o pipefail && xcodebuild test -workspace $XCODE_WORKSPACE -scheme $XCODE_SCHEME -destination "$XCODE_DESTINATION" | xcpretty
