name: CI

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Install Android SDK
        run: |
          export ANDROID_SDK_ROOT=$RUNNER_WORKSPACE/android-sdk
          mkdir -p $HOME/android-sdk
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -O android-sdk-tools.zip
          unzip -qq android-sdk-tools.zip -d $ANDROID_SDK_ROOT
          yes | $ANDROID_SDK_ROOT/cmdline-tools/bin/sdkmanager --licenses
          $ANDROID_SDK_ROOT/cmdline-tools/bin/sdkmanager "platforms;android-34" "build-tools;34.0.3"

      - name: Build Android
        run: ./gradlew assembleDebug
        working-directory: android

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build application
        run: npm run build
