name: Common

on: [workflow_call]

jobs:
  setup-node:
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install npm dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Lint
        run: npx eslint
