name: iOS CI

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  build-ios:
    name: Build iOS App
    uses: ./.github/workflows/common.yml
    with:
      runner: macos-latest
      node-version: '22'
    steps:
      - name: Install CocoaPods
        run: gem install cocoapods

      - name: Cache Pods
        uses: actions/cache@v4
        id: pods-cache
        with:
          path: ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install iOS dependencies
        run: cd ios && pod install

      - name: Build iOS
        run: cd ios && xcodebuild -workspace lumen_nextgen_mobile.xcworkspace -scheme lumen_nextgen_mobile -sdk iphonesimulator -configuration Debug build
